# fly.toml app configuration file generated for signalbrief-rsshub on 2025-05-23T06:43:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'signalbrief-rsshub'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 1200
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
